// Generates lib/oss_licenses.dart from pubspec.lock.
//
// dart_pubspec_licenses 3.0.4 (the newest version compatible with the Dart SDK
// shipped by Flutter 3.27) does not provide the `dart run
// dart_pubspec_licenses:generate` CLI entrypoint that newer releases do. It
// only exposes a library API. This script uses that library to emit a
// self-contained oss_licenses.dart file for the app's licenses screen.
//
// Usage: dart run tool/generate_oss_licenses.dart <projectRoot>

import 'dart:io' as io;

import 'package:dart_pubspec_licenses/dart_pubspec_licenses.dart' as oss;
import 'package:path/path.dart' as path;

String _escape(String s) => s.replaceAll("'", "\\'").replaceAll('\n', '\\n');

void main(List<String> args) async {
  final projectRoot = args.isEmpty ? io.Directory.current.path : args.first;
  final pubspecLockPath = path.join(projectRoot, 'pubspec.lock');
  if (!io.File(pubspecLockPath).existsSync()) {
    io.stderr.writeln('"$pubspecLockPath" not found.');
    io.exitCode = 1;
    return;
  }

  final deps = await oss.listDependencies(pubspecLockPath: pubspecLockPath);

  final buffer = StringBuffer()
    ..writeln('// dart format off')
    ..writeln('// cSpell:disable')
    ..writeln('// ignore_for_file: always_put_required_named_parameters_first')
    ..writeln('// ignore_for_file: constant_identifier_names')
    ..writeln('// ignore_for_file: sort_constructors_first')
    ..writeln()
    ..writeln('// This code was generated by tool/generate_oss_licenses.dart')
    ..writeln()
    ..writeln('class Package {')
    ..writeln("  const Package({required this.name, required this.description, this.license, required this.version});")
    ..writeln()
    ..writeln("  final String name;")
    ..writeln("  final String description;")
    ..writeln("  final String? license;")
    ..writeln("  final String version;")
    ..writeln('}')
    ..writeln()
    ..writeln('/// All dependencies including transitive dependencies.')
    ..writeln('const allDependencies = <Package>[');

  for (final dep in deps.allDependencies) {
    buffer
      ..writeln('  Package(')
      ..writeln("    name: '${_escape(dep.name)}',")
      ..writeln("    description: '${_escape(dep.description)}',")
      ..writeln("    version: '${_escape(dep.version)}',")
      ..writeln("    license: '${_escape(dep.license ?? '')}',")
      ..writeln('  ),');
  }

  buffer.writeln('];');
  buffer.writeln();

  final outFile = io.File(path.join(projectRoot, 'lib', 'oss_licenses.dart'));
  outFile.parent.createSync(recursive: true);
  outFile.writeAsStringSync(buffer.toString());
  io.stdout.writeln('Wrote ${outFile.path}');
}
